# Generated by Django 5.1.2 on 2024-10-20 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('dirlogo', models.CharField(max_length=50)),
                ('Horario_atencion', models.TimeField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('mision', models.TextField(max_length=100)),
                ('vision', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageRefugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('id_refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugio.refugio')),
            ],
        ),
    ]
