# Generated by Django 5.1.2 on 2024-10-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0002_alter_refugio_id_alter_refugio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='coordx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refugio',
            name='coordy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='dirlogo',
            field=models.ImageField(upload_to=''),
        ),
    ]
