# Generated by Django 5.1.2 on 2024-10-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0003_refugio_coordx_refugio_coordy_alter_refugio_dirlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugio',
            name='dirlogo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
