# Generated by Django 5.1.2 on 2024-10-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0004_alter_refugio_dirlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugio',
            name='mision',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='vision',
            field=models.CharField(max_length=100),
        ),
    ]
