# Generated by Django 5.1.2 on 2024-10-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0005_alter_refugio_mision_alter_refugio_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugio',
            name='mision',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='vision',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
