# Generated by Django 5.1.2 on 2024-10-21 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refugio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('descripcion', models.TextField(max_length=100)),
                ('raza', models.CharField(max_length=45)),
                ('peso', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('img_home_principal', models.ImageField(upload_to='')),
                ('img_print_mascota', models.ImageField(upload_to='')),
                ('estatus', models.CharField(max_length=45)),
                ('destacada', models.CharField(max_length=45)),
                ('id_refugio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='refugio.refugio')),
            ],
        ),
    ]
