# Generated by Django 5.1.2 on 2024-10-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='img_print_mascota1',
            new_name='img_print_mascota',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='img_print_mascota2',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='img_print_mascota3',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='img_print_mascota4',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
