# Generated by Django 5.1.2 on 2024-10-21 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
        ('refugio', '0002_alter_refugio_id_alter_refugio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='id_refugio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugio.refugio'),
        ),
    ]
