# Generated by Django 5.1.2 on 2024-10-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_alter_mascota_id_refugio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gato'), (2, 'Perro')], default=1),
        ),
    ]
