# Generated by Django 5.1.2 on 2024-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_mascota_destacada_alter_mascota_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'En Proceso'), (3, 'Adoptada')], default=1),
        ),
    ]
