# Generated by Django 5.1.2 on 2024-10-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_alter_mascota_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
