# Generated by Django 5.1.2 on 2024-10-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_mascota_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fecha_refugio',
            field=models.DateField(auto_now=True),
        ),
    ]
