# Generated by Django 5.1.2 on 2024-10-22 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0009_alter_mascota_fecha_refugio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_refugio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
