# Generated by Django 5.1.2 on 2024-10-22 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0010_alter_mascota_fecha_refugio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='Sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_refugio',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
