# Generated by Django 5.1.2 on 2024-10-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0011_mascota_sexo_alter_mascota_fecha_refugio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_mascota', models.ImageField(upload_to='')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
    ]
