# Generated by Django 5.1.2 on 2024-10-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0012_imagenesmascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
    ]
