# Generated by Django 5.1.2 on 2024-10-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id_adopcion', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
