# Generated by Django 5.1.2 on 2024-10-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='Habitantes',
            field=models.CharField(choices=[('1', 'Solo yo'), ('2', '2 a 5'), ('3', '5 ó mas')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='acepfamily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='animalescasa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='cerco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='conocuidado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='espacio',
            field=models.CharField(choices=[('1', 'Acceso a toda la casa'), ('2', 'Acceso restringido a algunos espacios'), ('3', 'Solo en mi habitación')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='espaciolibre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='motivo',
            field=models.CharField(choices=[('1', 'Por o para mis hijos'), ('2', 'Porque me gustan los animales'), ('3', 'Para regalar'), ('4', 'Por la compañía')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='mudanza',
            field=models.CharField(choices=[('1', 'Llevarlo conmigo'), ('2', 'Buscarle un nuevo hogar'), ('3', 'Dejarlo con un familiar o amigo'), ('4', 'Entregarlo a un refugio'), ('5', 'Abandonarlo')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='vacunados',
            field=models.BooleanField(default=False),
        ),
    ]
