# Generated by Django 5.1.2 on 2024-10-13 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Numero de telefono: '+999999999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
